title: "Chase Barnes — CS 499 Capstone ePortfolio"
description: "Professional self-assessment, code review, and enhanced artifacts in Software Design & Engineering, Algorithms & Data Structures, and Databases."
theme: jekyll-theme-cayman
show_downloads: false
